#!/bin/bash

echo "🚀 Railway Deployment Fix"
echo "=========================="
echo ""
echo "Your app is deployed at: https://web-production-168d.up.railway.app"
echo ""
echo "To fix the Google Sheets issue:"
echo ""
echo "1. Go to Railway Dashboard: https://railway.app/dashboard"
echo "2. Click on your project (diplomatic-trust)"
echo "3. Go to 'Variables' tab"
echo "4. Delete any existing GOOGLE_APPLICATION_CREDENTIALS variable"
echo "5. Click 'New Variable'"
echo "6. Name: GOOGLE_APPLICATION_CREDENTIALS"
echo "7. Value: Click 'Upload File' and select your credentials.json"
echo "8. Add these other variables:"
echo "   - NODE_ENV=production"
echo "   - JWT_SECRET=your-secure-secret"
echo "   - SPREADSHEET_ID_1=your_inventory_sheet_id"
echo "   - SPREADSHEET_ID_2=your_sales_sheet_id"
echo "   - SPREADSHEET_ID_3=your_purchases_sheet_id"
echo ""
echo "9. Your app will automatically redeploy"
echo ""
echo "✅ Your app will work after this!" 