services:
  - type: web
    name: stock-management-app
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPREADSHEET_ID_INVENTORY
        value: 1iQsQDnRrgP5LLhuimLny8doi6AEEgH-OibFnHRlCgPU
      - key: SPREADSHEET_ID_INVENTORY2
        value: 1Th-1fz4vKFJ6cO6t4rbTFNUhd1R0OtxJ_VlWQEhONk4
      - key: SPREADSHEET_ID_CUSTOMERS
        value: 1mn908aWMfAZrvxY16UbXoymqER1lW4G3ptiUZXFBYtA 