name: Daily Backup

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Create backup data
      run: |
        # Create backup directory
        mkdir -p backup-data
        
        # Copy important data files
        cp -r server/data backup-data/
        cp package.json backup-data/
        cp client/package.json backup-data/client-package.json
        
        # Create backup info
        echo "Backup created on $(date)" > backup-data/backup-info.txt
        echo "GitHub Actions automated backup" >> backup-data/backup-info.txt
        
    - name: Commit and push backup
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add backup files
        git add backup-data/
        
        # Commit with timestamp
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
        git commit -m "Automated daily backup: $TIMESTAMP" || echo "No changes to commit"
        
        # Push to repository
        git push origin main
        
    - name: Create backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: daily-backup-${{ github.run_number }}
        path: backup-data/
        retention-days: 30 